### ISSUE TITLE
cannot pass argument

### ISSUE THREAD

**Issue by tcurdt** [isometry/alfred-pipe#1]
TBH I am not sure why this isn't working for me. I enter "|" and all is good

![screen shot 2018-11-11 at 04 13 41](https://user-images.githubusercontent.com/13697/48308552-326a8000-e568-11e8-8a0a-f0d966be6e6a.png)

but as soon as I want to add the pipe command it turns into a search

![screen shot 2018-11-11 at 04 14 36](https://user-images.githubusercontent.com/13697/48308561-57f78980-e568-11e8-9894-bc1725601d24.png)

Given that the workflow expects an argument I am not sure what is going on

![screen shot 2018-11-11 at 04 15 19](https://user-images.githubusercontent.com/13697/48308568-7bbacf80-e568-11e8-8861-f48a7282ea01.png)

Any thoughts?
This is with Alfred 3.7

**Comment by isometry** [comment]
Did you ever get this working? I'm unable to reproduce the issue.

**Comment by tcurdt** [comment]
Still a problem with with Alfred 4.0.8

![pipe](https://user-images.githubusercontent.com/13697/76682898-12394e00-6600-11ea-9395-128c1cd0aed2.gif)

Anything I can do to help to debug this?

**Comment by isometry** [comment]
Certainly!

Could you please right click on the workflow in Alfred preferences, and select `Open in Terminal`, then run the following and attach the output?

```sh
/usr/bin/env python2.7 ./pipe.py base64
```

**Comment by tcurdt** [comment]
Well, that doesn't output much:

```
user.workflow.A30FEC54-A0D5-4028-B324-F554BC620F5D % /usr/bin/env python2.7 ./pipe.py base64
user.workflow.A30FEC54-A0D5-4028-B324-F554BC620F5D % 
```

What would you expect to see? I don't see a `main` method.

**Comment by tcurdt** [comment]
I assume this translates to `complete("base64")` which I now added as a test to `pipe.py`.
Which now gives:
```
% /usr/bin/env python2.7 ./pipe.py
Traceback (most recent call last):
  File "./pipe.py", line 123, in <module>
    complete("base64")
  File "./pipe.py", line 104, in complete
    aliases = fetch_aliases()
  File "./pipe.py", line 18, in fetch_aliases
    file = path.join(alfred.work(volatile=False), _path)
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A30FEC54-A0D5-4028-B324-F554BC620F5D/alfred.py", line 70, in work
    return _create(os.path.join(os.path.expanduser(path), bundleid))
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A30FEC54-A0D5-4028-B324-F554BC620F5D/alfred.py", line 83, in _create
    os.mkdir(path)
OSError: [Errno 2] No such file or directory: '/Users/user/Library/Application Support/Alfred 2/Workflow Data/net.isometry.alfred.pipe'
```
The actual path seems to be `~/Library/Application Support/Alfred/Workflow Data` not `~/Library/Application Support/Alfred 2/Workflow Data`

**Comment by tcurdt** [comment]
Chaning the path in `alfred.py` seem to make it work. But I am not sure what the other path and the `True/False` is meant to be.

```
def work(volatile):
    path = {
        True: '~/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data',
        False: '~/Library/Application Support/Alfred/Workflow Data'
    }[bool(volatile)]
    return _create(os.path.join(os.path.expanduser(path), bundleid))
```

**Comment by tcurdt** [comment]
But here is another bug:

`| grep 'foo'` works.
`| grep "foo"` again becomes a search.

**Comment by isometry** [comment]
It very much appears that you don't have [v1.2](https://github.com/isometry/alfred-pipe/releases/download/v1.2/pipe.alfredworkflow) installed…  could you please try re-installing and confirm that these issues persist? (Latest versions of my workflows are always on the Github releases page: https://github.com/isometry/alfred-pipe/releases)

`alfred.py` has relied on the `alfred_workflow_cache` and `alfred_workflow_data` environment variables since 23fed10346f34f0f182fc2ad009e936f54ac5e81 in 2016, and `pipe.py` has supported direct calling since 2017 😄

**Comment by tcurdt** [comment]
LOL - much better. Well, the issue is already ancient and I haven't used it forever since I didn't get it working. Your issue update only reminded me :)

But it seems I've opened it *after* the release of 1.2. Which is odd.
Anyway. I am happy now :)
Thanks!
