### ISSUE TITLE
Python3 support for use on macOS 12.3+

### ISSUE THREAD

**Issue by bmorgenthaler** [isometry/alfred-pipe#3]
As of macOS 12.3 Apple has removed python2.7 which this workflow is hardcoded to.  Are there plans to migrate to python 3 or is this workflow abandoned?

**Comment by isometry** [comment]
Not abandoned, I'll try to push an update tomorrow :-)

**Comment by isometry** [comment]
Fixed with [v1.3](https://github.com/isometry/alfred-pipe/releases/tag/v1.3)!
